services:
  # uncomment this section and comment out the mysql section to use postgres instead of mysql
  postgres:
    restart: unless-stopped
    image: ${DB_IMAGE}
    hostname: ${DB}
    volumes:
      - semaphore-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: semaphore
  # if you wish to use postgres, comment the mysql service section below
  # mysql:
  #   restart: unless-stopped
  #   image: mysql:8.0
  #   hostname: mysql
  #   volumes:
  #     - semaphore-mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  #     MYSQL_DATABASE: semaphore
  #     MYSQL_USER: semaphore
  #     MYSQL_PASSWORD: semaphore
  semaphore:
    depends_on:
      - ${DB} # for postgres, change to: postgres
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: ${DB} # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: ${DB_PORT} # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: ${DB} # for postgres, change to: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
      SEMAPHORE_LDAP_ACTIVATED: "no" # if you wish to use ldap, set to: 'yes'
      SEMAPHORE_LDAP_HOST: dc01.local.example.com
      SEMAPHORE_LDAP_PORT: "636"
      SEMAPHORE_LDAP_NEEDTLS: "yes"
      SEMAPHORE_LDAP_DN_BIND: "uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net"
      SEMAPHORE_LDAP_PASSWORD: "ldap_bind_account_password"
      SEMAPHORE_LDAP_DN_SEARCH: "dc=local,dc=example,dc=com"
      SEMAPHORE_LDAP_SEARCH_FILTER: "(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"
volumes:
  semaphore-postgres: # to use postgres, switch to: semaphore-postgres
