---

- hosts: oracle_vm
  become: true
  tasks: 
  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

  - name: install apache2 and php
    tags: apache,php,ubuntu
    package:
      name: 
        - "{{ apache_package  }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
